openapi: 3.0.0
info:
  title: Email enrollments
  version: v1
servers:
- url: https://{hostname}/amfa/v1
x-akamai:
  auth-type: EDGE_GRID
paths:
  /email-enrollments:
    $ref: paths/email-enrollments.yaml
