openapi: 3.0.0
info:
  title: Groups
  version: v1
servers:
- url: https://{hostname}/amfa/v1
x-akamai:
  auth-type: EDGE_GRID
paths:
  /groups:
    $ref: paths/groups.yaml
  /groups/{groupId}:
    $ref: paths/group.yaml
  /groups/{groupId}/users/{userId}:
    $ref: paths/user-per-group.yaml
