name: locationIds
in: query
description: |
  Filters the deployment history results by `locationId`. You can provide several comma-separated integer values. Returns all matching records regardless of other query parameters used.
required: false
explode: false
style: form
schema: 
  type: string
  example: "6908808,12260589,16791107"