type: object
description: | 
  ACL version rule statistics per deployment status.
properties:
  total:
    type: integer
    minimum: 0
    description: | 
      Total number of rules within the ACL version.
  installed:
    type: integer
    minimum: 0
    description: | 
      Number of successfully installed rules within the ACL version.
  notInstalled:
    type: integer
    minimum: 0
    description: | 
      Number of rules not yet installed within the ACL version.
  failed:
    type: integer
    minimum: 0
    description: |
      Number of failed rules within the ACL version.
additionalProperties: false