type: object
description: |
  ACL deployment status.
additionalProperties: false
properties:
  accountId:
    type: string
    description: | 
      Account ID.
  ruleSets:
    type: array
    description: | 
      Production, processing, and failed ACL versions.
    items:
      $ref: ../schemas/acl-deployment-status-by-state.yaml

