type: object
description:
  Status of rules within the ACL rule set.
properties:
  aclText:
    type: string
    description: | 
      ACL rule description. 
  ruleUuid:
    type: string
    description: | 
      The rule's unique ID.
  installStatus:
    type: string
    description: | 
      The rule's install status. Either `INSTALLED`, `NOT_INSTALLED`, or `FAILED`.
    enum:
      - INSTALLED
      - NOT_INSTALLED
      - FAILED
additionalProperties: false