openapi: 3.0.0
info:
  title: Demand
  version: v1
servers:
- url: https://{hostname}/gtm-api/v1/reports
tags:
- description: |
    Reports on demand percent versus actual demand percent seen by GTM rounded off to the nearest five minute interval for each data center.
  name: Directed demand
x-akamai:
  auth-type: EDGE_GRID
paths:
  /demand/domains/{domain}/properties/{property}:
    $ref: paths/property-demand.yaml
  /demand/domains/{domain}/properties/{property}/window:
    $ref: paths/demand-window.yaml
