openapi: 3.0.0
info:
  title: Load feedback
  version: v1
servers:
- url: https://{hostname}/gtm-api/v1/reports
tags:
- description: |
    Reports on the historical values of a given resource across all data centers and the given time period.
  name: Load feedback
x-akamai:
  auth-type: EDGE_GRID
paths:
  /load-feedback/domains/{domain}/window:
    $ref: paths/load-feedback-window.yaml
  /load-feedback/domains/{domain}/most-recent-load-data:
    $ref: paths/most-recent-load-data.yaml
  /load-feedback/domains/{domain}/resources/{resource}:
    $ref: paths/resource.yaml
