openapi: 3.0.0
info:
  title: IP availability
  version: v1
servers:
- url: https://{hostname}/gtm-api/v1/reports
tags:
- description: |
    Returns scores from Web agents to calculate server scores to make GTM liveness decisions.
  name: IP availability
x-akamai:
  auth-type: EDGE_GRID
paths:
  /ip-availability/domains/{domain}/properties/{property}:
    $ref: paths/property-ip-availability.yaml
