openapi: 3.0.0
info:
  title: Diagnostics
  version: v1
servers:
- url: https://{hostname}/gtm-api/v1/reports
tags:
- description: |
    Provides diagnostic data on how GTM is distributing traffic, including datacenter mapping decisions, per-IP routing logic, and map snapshot diffs.
  name: Diagnostics
x-akamai:
  auth-type: EDGE_GRID
paths:
  /diagnostics/datacenter/domains/{domain}:
    $ref: paths/diagnostics-datacenter.yaml
  /diagnostics/ip/domains/{domain}/properties/{property}:
    $ref: paths/diagnostics-ip.yaml
  /diagnostics/mapdiff/domains/{domain}:
    $ref: paths/diagnostics-mapdiff.yaml
  /diagnostics/mapdiff/domains/{domain}/datacenters/{datacenterId}/as/{asNumber}:
    $ref: paths/diagnostics-mapdiff-datacenter-as.yaml
  /diagnostics/mapdiff/domains/{domain}/datacenters/{datacenterId}/countries/{countryCode}:
    $ref: paths/diagnostics-mapdiff-datacenter-country.yaml
