openapi: 3.0.0
info:
  title: API endpoints
  version: v2
servers:
- url: https://{hostname}/api-definitions/v2
x-akamai:
  auth-type: EDGE_GRID
paths:
  /endpoints:
    $ref: paths/endpoints.yaml
  /endpoints/cloneEndpoint:
    $ref: paths/clone-endpoint.yaml
  /endpoints/files:
    $ref: paths/files.yaml
  /endpoints/user-entitlements:
    $ref: paths/user-entitlements.yaml
  /endpoints/verify-secure-connection:
    $ref: paths/verify-secure-connection.yaml
  /endpoints/{apiEndPointId}:
    $ref: paths/api-endpoint.yaml
  /endpoints/{apiEndPointId}/hide:
    $ref: paths/endpoint-hide.yaml
  /endpoints/{apiEndPointId}/show:
    $ref: paths/endpoint-show.yaml
  /endpoints/{apiEndPointId}/versions:
    $ref: paths/versions.yaml
  /endpoints/{apiEndPointId}/versions/{versionNumber}:
    $ref: paths/version-number.yaml
  /endpoints/{apiEndPointId}/versions/{versionNumber}/activate:
    $ref: paths/activate.yaml
  /endpoints/{apiEndPointId}/versions/{versionNumber}/cloneVersion:
    $ref: paths/clone-version.yaml
  /endpoints/{apiEndPointId}/versions/{versionNumber}/deactivate:
    $ref: paths/deactivate.yaml
  /endpoints/{apiEndPointId}/versions/{versionNumber}/file:
    $ref: paths/file.yaml
  /endpoints/{apiEndPointId}/versions/{versionNumber}/hide:
    $ref: paths/version-hide.yaml
  /endpoints/{apiEndPointId}/versions/{versionNumber}/piis:
    $ref: paths/piis.yaml
  /endpoints/{apiEndPointId}/versions/{versionNumber}/piis/parameters/{paramId}:
    $ref: paths/param.yaml
  /endpoints/{apiEndPointId}/versions/{versionNumber}/piis/settings:
    $ref: paths/settings.yaml
  /endpoints/{apiEndPointId}/versions/{versionNumber}/piis/status:
    $ref: paths/piis-status.yaml
  /endpoints/{apiEndPointId}/versions/{versionNumber}/piis/{piiId}:
    $ref: paths/pii.yaml
  /endpoints/{apiEndPointId}/versions/{versionNumber}/piis/{piiId}/status:
    $ref: paths/pii-status.yaml
  /endpoints/{apiEndPointId}/versions/{versionNumber}/resources:
    $ref: paths/resources.yaml
  /endpoints/{apiEndPointId}/versions/{versionNumber}/resources-detail:
    $ref: paths/resources-detail.yaml
  /endpoints/{apiEndPointId}/versions/{versionNumber}/resources/{apiResourceId}:
    $ref: paths/api-resource.yaml
  /endpoints/{apiEndPointId}/versions/{versionNumber}/show:
    $ref: paths/version-show.yaml
