openapi: 3.0.0
info:
  title: API delivery settings
  version: v2
servers:
- url: https://{hostname}/api-definitions/v2
x-akamai:
  auth-type: EDGE_GRID
paths:
  /endpoints/{apiEndPointId}/versions/{versionNumber}/settings/api-privacy:
    $ref: paths/api-privacy.yaml
  /endpoints/{apiEndPointId}/versions/{versionNumber}/settings/cache:
    $ref: paths/cache.yaml
  /endpoints/{apiEndPointId}/versions/{versionNumber}/settings/cors:
    $ref: paths/cors.yaml
  /endpoints/{apiEndPointId}/versions/{versionNumber}/settings/error-responses:
    $ref: paths/error-responses.yaml
  /endpoints/{apiEndPointId}/versions/{versionNumber}/settings/error-responses/{type}:
    $ref: paths/type.yaml
  /endpoints/{apiEndPointId}/versions/{versionNumber}/settings/graphql:
    $ref: paths/graphql.yaml
  /endpoints/{apiEndPointId}/versions/{versionNumber}/settings/gzip:
    $ref: paths/gzip.yaml
  /endpoints/{apiEndPointId}/versions/{versionNumber}/settings/jwt:
    $ref: paths/jwt.yaml
  /endpoints/{apiEndPointId}/versions/{versionNumber}/settings/routing:
    $ref: paths/routing.yaml
