openapi: 3.0.0
info:
  title: Resources and operations
  version: v2
servers:
- url: https://{hostname}/api-definitions/v2
x-akamai:
  auth-type: EDGE_GRID
paths:
  /endpoints/{endpointId}/versions/{versionNumber}/resources-and-operations:
    $ref: paths/resources-and-operations.yaml
  /endpoints/{endpointId}/versions/{versionNumber}/resources/{apiResourceId}/operations:
    $ref: paths/operations.yaml
  /endpoints/{endpointId}/versions/{versionNumber}/resources/{apiResourceId}/operations/{operationId}:
    $ref: paths/operation.yaml
  /search-operations:
    $ref: paths/search-operations.yaml
  /verify-operations:
    $ref: paths/verify-operations.yaml
