type: object
description: |-
  Custom rule usage data.
  
x-akamai:
  file-path: schemas/config-custom-rules-usage-response.yaml
additionalProperties: false
required:
- rules
properties:
  rules:
    type: array
    description: |
      The requested custom rule IDs and names of the security policies that use them.
    nullable: false
    minItems: 0
    uniqueItems: true
    items:
      type: object
      description: |
        Usage of the requested custom rule in security policies.
      additionalProperties: false
      required:
      - ruleId
      - policies
      properties:
        policies:
          type: array
          description: |
            A list of security policies which use the custom rule.
          nullable: false
          minItems: 0
          uniqueItems: true
          items:
            type: object
            description: |
              A security policy using the custom rule.
            additionalProperties: false
            required:
            - policyId
            - policyName
            properties:
              policyId:
                type: string
                description: |
                  A security policy ID.
                nullable: false
              policyName:
                type: string
                description: |
                  A security policy name.
                nullable: false
        ruleId:
          type: integer
          description: |
            A custom rule ID.
          nullable: false
