type: object
description: |-
  Contains Security Information Event Management (SIEM) integration settings.
  
x-akamai:
  file-path: schemas/siem-settings.yaml
additionalProperties: false
required:
- enableSiem
properties:
  enableForAllPolicies:
    type: boolean
    description: |
      Whether you enabled SIEM for all the security policies in the configuration version.
  enableSiem:
    type: boolean
    description: |
      Whether you enabled SIEM in a security configuration version.
  enabledBotmanSiemEvents:
    type: boolean
    description: |
      __Deprecated__ Whether you enabled SIEM for the Bot Manager events. Use `exceptions` parameter instead to set botman siem events exception.
    x-akamai:
      status: DEPRECATED
    deprecated: true
  exceptions:
    type: array
    description: |
      Describes all attack type exceptions that will be ignored in SIEM events.
    items:
      type: object
      additionalProperties: false
      properties:
        actionTypes:
          type: array
          description: |
            Describes [actions](https://techdocs.akamai.com/application-security/reference/siem-action-and-attack-type-exceptions) to be excluded for a particular attack type. A `*` value means all actions.
          items:
            type: string
            enum:
            - '*'
            - alert
            - deny
            - all_custom
            - abort
            - allow
            - delay
            - ignore
            - monitor
            - slow
            - tarpit
        protection:
          type: string
          description: |
            [Attack types](https://techdocs.akamai.com/application-security/reference/siem-action-and-attack-type-exceptions) to be added as an exception.
          enum:
          - ipgeo
          - rate
          - urlProtection
          - slowpost
          - customrules
          - waf
          - apirequestconstraints
          - clientrep
          - malwareprotection
          - botmanagement
          - aprProtection
          - aifirewallprotection
  firewallPolicyIds:
    type: array
    description: |
      The list of security policy identifiers for which to enable the SIEM integration.
    items:
      type: string
  includeJA4FingerprintToSiem:
    type: boolean
    description: |
      Whether you enabled JA4 header forwarding for SIEM.
  siemDefinitionId:
    type: integer
    description: |
      Uniquely identifies the SIEM settings.
