openapi: 3.0.0
info:
  title: Tests
  version: v1
servers:
- url: https://{hostname}/sla-api/v1
tags:
- description: Groups operations that you can use to manage test configurations.
  name: Tests
x-akamai:
  auth-type: EDGE_GRID
paths:
  /tests:
    $ref: paths/tests.yaml
  /tests/{slaTestId}:
    $ref: paths/sla-test.yaml
  /tests/{slaTestId}/reports/availability:
    $ref: paths/availability.yaml
  /tests/{slaTestId}/reports/performance:
    $ref: paths/performance.yaml
