type: object
description: |
  Deployment details.
additionalProperties: false
required:
- id
- status
- message
- comment
- startTime
- deployedBy
- progressPct
properties:
  id:
    type: integer
    description: |
      Unique identifier of the deployment.
    minimum: 1
  status:
    type: string
    description: |
      Specifies the deployment status. Refer to [Deployment status](ref:deployment-status) for more information.
    enum:
    - CONTENT_EXTERNAL
    - REVERTING
    - STAGING
    - PENDING
    - RUNNING
    - COMPLETED
    - FAILED
    - BUILDING
    - AUTO_RKS_ONLY
  message:
    type: string
    description: |
      Deployment details.
    minLength: 1
  comment:
    type: string
    description: |
      Deployment comment.
    minLength: 1
  changes: 
    type: string
    description: | 
      The deployment configuration changes made, represented as a JSON-formatted string. 
  startTime:
    type: string
    description: |
      The deployment's start time.
    readOnly: true
    format: date-time
  endTime:
    type: string
    description: |
      The deployment's end time.
    readOnly: true
    format: date-time
  deployedBy:
    type: string
    description: |
      User who initiated the deployment.
    readOnly: true
    minLength: 1
  progressPct:
    type: integer
    description: |
      Indicates the deployment's progress as a percentage.
    minimum: 0
    maximum: 100
