type: object
description: |
  Specifies notification configuration details.
additionalProperties: false
required:
- type
- value
- id
- createdBy
- createdDate
- siteSelectionStrategy
- siteMappings
- attributes
properties:
  id:
    type: integer
    description: |
      A unique identifier for notification config.
    minimum: 1
  type:
    type: string
    description: |
      The subscriber notification method. Either `alert`, `upgrade`, `vmUpgrade`, `scheduledReport`, `email`, or `system`.
    enum:
    - alert
    - upgrade
    - vmUpgrade
    - scheduledReport
    - system
    - email
  value:
    type: string
    description: |
      The email of the subscriber.
  createdBy:
    type: string
    description: |
      Name of the user who created this notification config.
    minLength: 1
  createdDate:
    type: string
    description: |
      ISO 8601 timestamp marking this notification config's creation.
    readOnly: true
    format: date-time
  modifiedBy:
    type: string
    description: |
      Name of the user who most recently modified this notification config.
    minLength: 1
  modifiedDate:
    type: string
    description: |
      ISO 8601 timestamp marking this notification config's last modification.
    readOnly: true
    format: date-time
  siteSelectionStrategy:
    type: string
    description: |
      The location strategy adopted for notification, either `ALL` or `PARTIAL`.
    enum:
    - ALL
    - PARTIAL
  siteMappings:
    type: array
    description: |
      Site mappings for the notification config.
    minItems: 0
    items:
      type: object
      additionalProperties: false
      required:
      - siteId
      - siteName
      properties:
        siteId:
          type: integer
          description: |
            Unique identifier of site for the notifications.
          minimum: 1
        siteName:
          type: string
          description: |
            Name of site for the notifications.
          minLength: 1
  attributes:
    type: array
    description: |
      Notification attributes.
    minItems: 0
    items:
      type: object
      additionalProperties: false
      required:
      - category
      - contentType
      - enabled
      properties:
        category:
          type: string
          description: |
            The category of notification. Either `alert`, `upgrade`, `vmUpgrade`, `scheduledReport`, `email`, or `system`.
          enum:
          - alert
          - upgrade
          - vmUpgrade
          - scheduledReport
          - system
          - email
          minLength: 1
        contentType:
          type: string
          description: |
            The notification's MIME type, either `text/html` or `text/plain`.
          enum:
          - text/html
          - text/plain
          minLength: 1
        enabled:
          type: boolean
          description: |
            Enables the notification.
