x-akamai:
  path-info: /contracts/{contractId}/groups/{groupId}/hosts
parameters:
- $ref: ../parameters/group-id-path.yaml
- $ref: ../parameters/contract-id-path.yaml
get:
  operationId: get-contract-group-hosts
  summary: List hostnames
  tags:
  - Contracts and groups
  description: |
    Lists all hostnames through which API consumers can access an endpoint service under a given contract and group pairing. You can use Property Manager (or [PAPI](https://techdocs.akamai.com/property-mgr/reference/api)) to create new hostnames to make available to users.
  responses:
    200:
      description: |
        The response lists hosts for the contract and group.
      content:
        application/json:
          example:
            $ref: ../examples/api-endpoint-hosts-dto-example.json
          schema:
            $ref: ../schemas/hosts-schema.yaml
    403:
      description: |
        [Forbidden](ref:403). You don't have permission to read the API endpoint for the specified contract and group.
      $ref: ../errors/403.yaml
