x-akamai:
  path-info: /endpoints/{apiEndPointId}/versions/{versionNumber}/piis/parameters/{paramId}
parameters:
- $ref: ../parameters/api-end-point-id-path.yaml
- $ref: ../parameters/version-number-path.yaml
- $ref: ../parameters/param-id-path.yaml
post:
  operationId: post-endpoint-version-piis-parameter
  summary: Add or update a user-created PII instance
  tags:
  - Personally identifiable information
  description: |
    Adds or updates PII in an API parameter. This is for you to add to or modify in your API definition yourself, rather than the network discovering the PII for you.
  requestBody:
    required: true
    content:
      application/json:
        example:
          $ref: ../examples/pii-update-example.json
        schema:
          $ref: ../schemas/pii-update-type-dto.yaml
  responses:
    204:
      description: |
        Successfully added or updated PII.
    404:
      description: |
        [Not found](ref:404). Can't find the parameter ID.
      $ref: ../errors/404.yaml
