openapi: 3.0.3
info:
  title: Targets
  version: v1
servers:
- url: https://{hostname}/prolexic-network-health/v1
- url: http://prolexic-network-health/v1
tags:
- description: |
    Manage network targets for monitoring and health checks.
  name: Targets
x-akamai:
  auth-type: EDGE_GRID
paths:
  /targets:
    $ref: paths/targets.yaml
  /targets/{targetId}:
    $ref: paths/targets-id.yaml