x-akamai:
  path-info: /configurations
get:
  operationId: get-configurations
  summary: List CAC configurations
  tags:
  - CAC configurations
  description: |
    Lists all Client Access Control (CAC) configurations you can access.
  responses:
    200:
      description: |
        The response returns CAC configurations.
      content:
        application/json:
          example:
            $ref: ../examples/get-configurations.json
          schema:
            $ref: ../schemas/configurations.yaml
    400:
      $ref: ../errors/400.yaml
    401:
      $ref: ../errors/401.yaml
    403:
      $ref: ../errors/403.yaml
    404:
      $ref: ../errors/404.yaml
    405:
      $ref: ../errors/405.yaml
    406:
      $ref: ../errors/406.yaml
    500:
      $ref: ../errors/500.yaml
