x-akamai:
  path-info: /configurations/{configurationId}
parameters:
- $ref: ../parameters/configuration-id-path.yaml
get:
  operationId: get-configuration
  summary: Get a CAC configuration
  tags:
  - CAC configurations
  description: |
    Returns the Client Access Control (CAC) configuration for a specific `configurationId`.
  responses:
    200:
      description: |
        The response returns a CAC configuration.
      content:
        application/json:
          example:
            $ref: ../examples/get-configuration.json
          schema:
            $ref: ../schemas/configuration.yaml
    400:
      $ref: ../errors/400.yaml
    401:
      $ref: ../errors/401.yaml
    403:
      $ref: ../errors/403.yaml
    404:
      $ref: ../errors/404.yaml
    405:
      $ref: ../errors/405.yaml
    406:
      $ref: ../errors/406.yaml
    500:
      $ref: ../errors/500.yaml
