openapi: 3.0.0
info:
  title: Categories
  version: v1
servers:
- url: https://{hostname}/case-management/v3
tags:
- description: List available case categories.
  name: Case categories
x-akamai:
  auth-type: EDGE_GRID
paths:
  /categories/{categoryId}:
    $ref: paths/category.yaml
