openapi: 3.0.0
info:
  title: Requests
  version: v1
servers:
- url: https://{hostname}/eccu-api/v1
x-akamai:
  auth-type: EDGE_GRID
paths:
  /requests:
    $ref: paths/requests.yaml
  /requests/{requestId}:
    $ref: paths/request.yaml
