openapi: 3.0.0
info:
  title: Events
  version: v1
servers:
- url: https://{hostname}/event-viewer-api/v1
tags:
- description: |
    Get data about portal events stored in event logs in either JSON or
    CSV format
  name: Events
x-akamai:
  auth-type: EDGE_GRID
paths:
  /events:
    $ref: paths/events.yaml
