openapi: 3.0.0
info:
  title: Event types
  version: v1
servers:
- url: https://{hostname}/event-viewer-api/v1
tags:
- description: |
    Get data about user-defined events.
  name: Event types
x-akamai:
  auth-type: EDGE_GRID
paths:
  /event-types:
    $ref: paths/event-types.yaml
