openapi: 3.0.0
info:
  title: Data Loss Prevention Dictionary
  version: v3
servers:
- url: https://{hostname}/etp-config/v3
tags:
- description: |
    Data loss prevention (DLP) allows SIA to identify and block sensitive or confidential data uploaded from a corporate network and transmitted to the public Internet over an HTTP or HTTPS connection. A DLP dictionary contains the regular expression patterns that are used to find this information.
  name: DLP dictionaries
- description: |
    The patterns used by a DLP dictionary to detect data loss.
  name: DLP dictionary patterns
- description:
    The regular expressions used by a DLP dictionary to detect data loss.
  name: DLP regexes
x-akamai:
  auth-type: EDGE_GRID
paths:
  /configs/{configId}/dictionaries:
    $ref: paths/dictionaries.yaml
  /configs/{configId}/dictionaries/{dictionaryId}:
    $ref: paths/dictionary.yaml
  /configs/{configId}/patterns:
    $ref: paths/patterns.yaml
  /configs/{configId}/patterns/regexes:
    $ref: paths/regexes.yaml
  /configs/{configId}/patterns/regexes/{regexId}:
    $ref: paths/regex.yaml
  /configs/{configId}/patterns/{patternId}:
    $ref: paths/pattern.yaml
