openapi: 3.0.0
info:
  title: Custom responses
  version: v3
servers:
- url: https://{hostname}/etp-config/v3
tags:
- description: |
    A custom response configuration allows you to direct suspicious traffic to a machine in your network where activity is recorded. Information about the user device that made the request is captured to discover the internal IP addresses of infected machines on the corporate network.
  name: Custom responses
x-akamai:
  auth-type: EDGE_GRID
paths:
  /configs/{configId}/honeypots:
    $ref: paths/honeypots.yaml
  /configs/{configId}/honeypots/{honeypotId}:
    $ref: paths/honeypot.yaml
