openapi: 3.0.0
info:
  title: Client Configurations
  version: v3
servers:
- url: https://{hostname}/etp-config/v3
tags:
- description: |
    Enables managing client configurations. The operations include the SIA clients and network configuration along with version management and ability to activate and deactivate on demand.
  name: Client configuration
- description: |
    Tracks the client software versions deployed.
  name: Client versions
- description: |
    Tracks the devices the SIA client is installed on.
  name: Client devices
- description: |
    Configures network access settings for client devices.
  name: Client network configurations
x-akamai:
  auth-type: EDGE_GRID
paths:
  /configs/{configId}/client-configuration:
    $ref: paths/client-configuration.yaml
  /configs/{configId}/client-versions:
    $ref: paths/client-versions.yaml
  /configs/{configId}/client-versions/op/rotate-entitlement-code:
    $ref: paths/rotate-entitlement-code.yaml
  /configs/{configId}/client-versions/{clientVersionId}:
    $ref: paths/client-version.yaml
  /configs/{configId}/client-versions/{clientVersionId}/download:
    $ref: paths/download.yaml
  /configs/{configId}/client/devices:
    $ref: paths/devices.yaml
  /configs/{configId}/client/devices/{deviceId}/op/de-activate:
    $ref: paths/de-activate.yaml
  /configs/{configId}/client/devices/{deviceId}/op/re-activate:
    $ref: paths/re-activate.yaml
  /configs/{configId}/client/status:
    $ref: paths/status.yaml
  /configs/{configId}/network-configuration:
    $ref: paths/network-configuration.yaml
