openapi: 3.0.0
info:
  title: Notifications
  version: v3
servers:
- url: https://{hostname}/etp-config/v3
tags:
- description: |
    Configures notifications based on the location, threat category, or report type.
  name: Notifications
x-akamai:
  auth-type: EDGE_GRID
paths:
  /configs/{configId}/notifications-config:
    $ref: paths/notifications-config.yaml
  /configs/{configId}/notifications-config/{notificationType}:
    $ref: paths/notification-type.yaml
