openapi: 3.0.0
info:
  title: Connection Credentials
  version: v3
servers:
- url: https://{hostname}/etp-config/v3
tags:
- description: |
    Enables the SIA proxy to authorize connections from the on-premises proxy in a proxy chaining configuration. This setting adds the `Proxy-Authorization` header to these connections. The `Proxy-Authorization` header contains proxy credentials that authenticate the on-premises VPN. ETP validates these credentials before it allows connections from the on-premises VPN.
  name: VPN credentials
- description: |
    Enables the SIA proxy to authorize connections from the on-premises proxy in a proxy chaining configuration. This setting adds the `Proxy-Authorization` header to these connections. The `Proxy-Authorization` header contains proxy credentials that authenticate the on-premises proxy. The SIA proxy validates these credentials before it allows connections from the on-premises proxy.
  name: Proxy credentials
x-akamai:
  auth-type: EDGE_GRID
paths:
  /configs/{configId}/proxy-credentials:
    $ref: paths/proxy-credentials.yaml
  /configs/{configId}/proxy-credentials/{userName}:
    $ref: paths/user-name.yaml
  /configs/{configId}/vpn-credentials:
    $ref: paths/vpn-credentials.yaml
  /configs/{configId}/vpn-credentials/{ikeId}:
    $ref: paths/ike.yaml
