openapi: 3.0.0
info:
  title: Tenant and Delegated Access
  version: v3
servers:
- url: https://{hostname}/etp-config/v3
tags:
- description: |
    Tenant access is used by Managed Service Providers (MSP) to restrict and create separate access for individual customers. These same settings help you delegate access within an organization.
  name: Tenants
x-akamai:
  auth-type: EDGE_GRID
paths:
  /configs/{configId}/onboard-tenant:
    $ref: paths/onboard-tenant.yaml
  /configs/{configId}/tenants:
    $ref: paths/tenants.yaml
  /configs/{configId}/tenants/{tenantId}:
    $ref: paths/tenant.yaml
  /configs/{configId}/tenants/{tenantId}/users:
    $ref: paths/users.yaml
