type: object
description: |
  A method's privacy settings.
additionalProperties: false
properties:
  public:
    type: boolean
    description: |
      Whether the method is public, that is, accessible without an API key.
  inheritsFromEndpoint:
    type: boolean
    description: |
      Whether the method inherits the resource's API privacy settings.
    readOnly: true
