type: object
description: |
  API privacy settings configured for an endpoint and its associated resources. You can configure API privacy settings if the API Gateway product is in your contract.
additionalProperties: false
required:
- public
properties:
  public:
    type: boolean
    description: |
      Whether the endpoint is public, that is, accessible without an API key.
  resources:
    type: object
    description: |
      Specifies each resource's privacy settings. This object is a map of resource IDs to API privacy settings. Applies only when `public` is set to `false`.
    additionalProperties:
      $ref: api-privacy-settings-resource-id.yaml
