type: object
description: |
  Describes the full PII object.
additionalProperties: false
required:
- constraints
- exclusions
properties:
  constraints:
    $ref: pii-constraints-dto.yaml
  exclusions:
    type: array
    description: |
      Parameters you want to exclude from inspecting and enforcing constraints.
    items:
      $ref: pii-exclusion-dto.yaml
