openapi: 3.0.0
info:
  title: Services
  version: v1
servers:
- url: https://{hostname}/firewall-rules-manager/v1
x-akamai:
  auth-type: EDGE_GRID
paths:
  /services:
    $ref: paths/services.yaml
  /services/{serviceId}:
    $ref: paths/service.yaml
