openapi: 3.0.0
info:
  title: Domains
  version: v1
servers:
- url: https://{hostname}/config-gtm/v1
x-akamai:
  auth-type: EDGE_GRID
paths:
  /domains:
    $ref: paths/domains.yaml
  /domains/{domainName}:
    $ref: paths/domain.yaml
  /domains/{domainName}/authorities:
    $ref: paths/domain-authorities.yaml
  /domains/{domainName}/history:
    $ref: paths/history.yaml
