openapi: 3.0.0
info:
  title: Resources
  version: v1
servers:
- url: https://{hostname}/config-gtm/v1
x-akamai:
  auth-type: EDGE_GRID
paths:
  /domains/{domainName}/resources:
    $ref: paths/resources.yaml
  /domains/{domainName}/resources/{resourceName}:
    $ref: paths/resource.yaml
