openapi: 3.0.0
info:
  title: Properties
  version: v1
servers:
- url: https://{hostname}/config-gtm/v1
x-akamai:
  auth-type: EDGE_GRID
paths:
  /domains/{domainName}/properties:
    $ref: paths/properties.yaml
  /domains/{domainName}/properties/{propertyName}:
    $ref: paths/property.yaml
