openapi: 3.0.0
info:
  title: CIDR maps
  version: v1
servers:
- url: https://{hostname}/config-gtm/v1
x-akamai:
  auth-type: EDGE_GRID
paths:
  /domains/{domainName}/cidr-maps:
    $ref: paths/cidr-maps.yaml
  /domains/{domainName}/cidr-maps/{mapName}:
    $ref: paths/cidr-map.yaml
