openapi: 3.0.0
info:
  title: Autonomous system maps
  version: v1
servers:
- url: https://{hostname}/config-gtm/v1
x-akamai:
  auth-type: EDGE_GRID
paths:
  /domains/{domainName}/as-maps:
    $ref: paths/as-maps.yaml
  /domains/{domainName}/as-maps/{mapName}:
    $ref: paths/map-as.yaml
