openapi: 3.0.0
info:
  title: Geographic maps
  version: v1
servers:
- url: https://{hostname}/config-gtm/v1
x-akamai:
  auth-type: EDGE_GRID
paths:
  /domains/{domainName}/geographic-maps:
    $ref: paths/geo-maps.yaml
  /domains/{domainName}/geographic-maps/{mapName}:
    $ref: paths/map-geo.yaml
