openapi: 3.0.0
info:
  title: Data centers
  version: v1
servers:
- url: https://{hostname}/config-gtm/v1
x-akamai:
  auth-type: EDGE_GRID
paths:
  /domains/{domainName}/datacenters:
    $ref: paths/data-centers.yaml
  /domains/{domainName}/datacenters/datacenter-for-ip-version-selector-ipv4:
    $ref: paths/data-center-ipv4.yaml
  /domains/{domainName}/datacenters/datacenter-for-ip-version-selector-ipv6:
    $ref: paths/data-center-ipv6.yaml
  /domains/{domainName}/datacenters/default-datacenter-for-maps:
    $ref: paths/data-center-default.yaml
  /domains/{domainName}/datacenters/{datacenterId}:
    $ref: paths/data-center.yaml
