openapi: 3.0.0
info:
  title: Collections
  version: v1
servers:
- url: https://{hostname}/config-gtm/v1
x-akamai:
  auth-type: EDGE_GRID
paths:
  /collections/akamai-cloud-regions:
    $ref: paths/akamai-cloud-regions.yaml
  /collections/datacenter-ids:
    $ref: paths/datacenter-ids.yaml
  /collections/supported-geo-codes:
    $ref: paths/supported-geo-codes.yaml
  /data/recordset-types:
    $ref: paths/recordset-types.yaml
