openapi: 3.0.0
info:
  title: Download notifications
  version: v1
servers:
- url: https://{hostname}/ota/v1
x-akamai:
  auth-type: EDGE_GRID
paths:
  /download-notifications/{cpcode}:
    $ref: paths/download-notifications.yaml
tags:
  - name: Download notifications
    description: |
      Get information about notifications for completed downloads to specific vehicles.