openapi: 3.0.0
info:
  title: Invalidations
  version: v3
servers:
- url: https://{hostname}/ccu/v3
x-akamai:
  auth-type: EDGE_GRID
paths:
  /invalidate/cpcode/{network}:
    $ref: paths/invalidate-cpcode.yaml
  /invalidate/tag/{network}:
    $ref: paths/invalidate-tag.yaml
  /invalidate/url/{network}:
    $ref: paths/invalidate-url.yaml
