openapi: 3.0.0
info:
  title: Threat event reports
  version: v3
servers:
- url: https://{hostname}/etp-report/v3
tags:
- description: |
    Generate reports on detected and blocked threat events based on your custom SIA security lists.
  name: Threat events
x-akamai:
  auth-type: EDGE_GRID
paths:
  /configs/{configId}/threat-events/aggregate:
    $ref: paths/threat-events-aggregate.yaml
  /configs/{configId}/threat-events/details:
    $ref: paths/threat-events-details.yaml
  /configs/{configId}/threat-events/time-series:
    $ref: paths/threat-events-time-series.yaml
