openapi: 3.0.0
info:
  title: AUP event reports
  version: v3
servers:
- url: https://{hostname}/etp-report/v3
tags:
- description: |
    Generate reports about Acceptable User Policy (AUP) events or get information about existing AUP events.
  name: AUP events
x-akamai:
  auth-type: EDGE_GRID
paths:
  /configs/{configId}/aup-events/aggregate:
    $ref: paths/aup-events-aggregate.yaml
  /configs/{configId}/aup-events/details:
    $ref: paths/aup-events-details.yaml
  /configs/{configId}/aup-events/time-series:
    $ref: paths/aup-events-time-series.yaml
