openapi: 3.0.0
info:
  title: Security Connector event reports
  version: v3
servers:
- url: https://{hostname}/etp-report/v3
tags:
- description: |
    Generate Security Connector reports. Security Connector events provide details on malicious or suspicious traffic that SIA routes to a sinkhole device.
  name: Security Connector event reports
x-akamai:
  auth-type: EDGE_GRID
paths:
  /configs/{configId}/sinkhole-events/aggregate:
    $ref: paths/sinkhole-events-aggregate.yaml
  /configs/{configId}/sinkhole-events/details:
    $ref: paths/sinkhole-events-details.yaml
  /configs/{configId}/sinkhole-events/time-series:
    $ref: paths/sinkhole-events-time-series.yaml
