openapi: 3.0.0
info:
  title: IDP systems reports
  version: v3
servers:
- url: https://{hostname}/etp-report/v3
tags:
- description: |
    Get information about identity provider (IdP) access logs.
  name: IDP access logs
x-akamai:
  auth-type: EDGE_GRID
paths:
  /configs/{configId}/access-logs/details:
    $ref: paths/access-logs-details.yaml
