openapi: 3.0.0
info:
  title: DeepScan event reports
  version: v3
servers:
- url: https://{hostname}/etp-report/v3
tags:
- description: |
    Generate reports of deepscan data for a configuration's offline network.
  name: Deepscan reports
x-akamai:
  auth-type: EDGE_GRID
paths:
  /configs/{configId}/deep-scan-reports:
    $ref: paths/deep-scan-reports.yaml
