openapi: 3.0.0
info:
  title: Threat intelligence
  version: v3
servers:
  - url: https://{hostname}/etp-report/v3
tags:
  - description: | 
      Provides the latest domain threat intelligence data as a gzipped CSV.
    name: Threat intelligence
x-akamai:
  auth-type: EDGE_GRID
paths:
  /threat-intel/domains/latest/check:
    $ref: paths/threat-intel-feed.yaml