openapi: 3.0.0
info:
  title: Contracts
  version: v1
servers:
- url: https://{hostname}/contract-api/v1
x-akamai:
  auth-type: EDGE_GRID
paths:
  /contracts/identifiers:
    $ref: paths/contract-ids.yaml
  /contracts/{contractId}/products/summaries:
    $ref: paths/contract-summaries.yaml
