title: datacenter v1.3
allOf:
- $ref: datacenter-vnd-config-gtm.v1.2.yaml
- type: object
  description: |
    The data centers in the GTM domain.
  additionalProperties: true
  properties:
    scorePenalty:
      type: integer
      description: |
        Influences the score for a data center. Giving a positive penalty increases the score and drives traffic away from the data center. Giving a negative penalty reduces the score and draws in more traffic that would otherwise go elsewhere. As the score is measured in milliseconds of ping time, very small numbers like 1 or 2 have virtually no effect. Typically, penalties are given in the tens or hundreds. Note that `scorePenalty` applies only for properties that use performance load balancing.
      x-akamai:
        labels:
        - v1.3
    cloudServerHostHeaderOverride:
      type: boolean
      description: |
        Balances load between two or more servers in a cloud environment. Either `true` if cloud server targeting is enabled or `false` if not.
      x-akamai:
        labels:
        - v1.3
