title: datacenter v1.7
allOf:
- $ref: datacenter-vnd-config-gtm.v1.6.yaml
- type: object
  description: |
    The data centers in the GTM domain.
  additionalProperties: true
  properties:
    cloud:
      type: object
      description: |
        Identifies the cloud provider and region for this data center.
      x-akamai:
        labels:
        - v1.7
      additionalProperties: false
      nullable: true
      properties:
        provider:
          type: string
          description: |
            The cloud provider for this data center.
        regionId:
          type: string
          description: |
            The cloud region identifier for this data center.
