title: Domain v1.4
allOf:
- $ref: domain-vnd-config-gtm.v1.1-base.yaml
- type: object
  description: |
    The basic building block of a traffic management configuration. Each domain object represents a complete GTM domain such as `example.akadns.net`.
  additionalProperties: true
  required:
  - datacenters
  - properties
  properties:
    properties:
      type: array
      description: |
        The properties in the GTM domain.
      items:
        $ref: property-vnd-config-gtm.v1.4.yaml
    datacenters:
      type: array
      description: |
        The set of data centers assigned to this domain.
      items:
        $ref: datacenter-vnd-config-gtm.v1.4.yaml
