type: object
description: |
  Summary information about the domain.
additionalProperties: true
properties:
  name:
    type: string
    description: |
      The full GTM domain name that needs to end in `.akadns.net`, up to 100 characters.
    minLength: 1
    maxLength: 100
  status:
    type: string
    description: |
      Describes the status of the domain.
  acgId:
    type: string
    description: |
      The contract Id of the domain.
  lastModified:
    type: string
    description: |
      An ISO 8601 timestamp that indicates the time of the last domain change.
    readOnly: true
  deleteRequestId:
    type: string
    description: |
      Unique identifier of the delete request associated with the domain. Used for tracking and auditing deletion operations within the system.
    nullable: true
  signAndServe:
    type: boolean
    description: |
      Whether DNSSEC Sign&Serve is enabled.
    default: false
  signAndServeAlgorithm:
    type: string
    description: |
      The algorithm currently or last used for DNSSEC Sign&Serve. The value is `null` if no algorithm has ever been assigned to this domain. Either `RSA_SHA1`, `RSA_SHA256`, `RSA_SHA512`, `ECDSA_P256_SHA256`, `ECDSA_P384_SHA384`.
    nullable: true
    enum:
    - RSA_SHA1
    - RSA_SHA256
    - RSA_SHA512
    - ECDSA_P256_SHA256
    - ECDSA_P384_SHA384
  links:
    type: array
    description: |
      A URL path that allows direct navigation to the domain.
    items:
      $ref: link.yaml
