openapi: 3.0.0
info:
  title: Access Revocation
  version: v2
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
servers:
- url: https://{hostname}/taas/v2
x-akamai:
  auth-type: EDGE_GRID
  file-path: access-revocation.yaml
paths:
  /revocation-lists:
    $ref: paths/revocation-lists.yaml
  /revocation-lists/{revocationListId}:
    $ref: paths/revocation-list.yaml
  /revocation-lists/{revocationListId}/identifiers:
    $ref: paths/identifiers.yaml
  /revocation-lists/{revocationListId}/identifiers/add:
    $ref: paths/identifiers-add.yaml
  /revocation-lists/{revocationListId}/identifiers/remove:
    $ref: paths/identifiers-remove.yaml
  /revocation-lists/{revocationListId}/identifiers/{tokenId}:
    $ref: paths/identifier.yaml
  /revocation-lists/{revocationListId}/meta:
    $ref: paths/revocation-list-meta.yaml
  /revocation-lists/{revocationListId}/properties:
    $ref: paths/properties.yaml
