x-akamai:
  path-info: /enrollments/{enrollmentId}/deployments/staging
parameters:
- $ref: ../parameters/enrollment-id-path.yaml
get:
  operationId: get-deployment-staging
  summary: Get staging deployment
  tags:
  - Deployments
  description: |
    Gets the enrollments deployed on the staging network.
  responses:
    200:
      description: |
        The response reflects your deployment's details to the staging network.
      content:
        application/vnd.akamai.cps.deployment.v8+json:
          example:
            $ref: ../examples/deployment.v8.json
          schema:
            $ref: ../schemas/deployment.v8.yaml
