openapi: 3.0.0
info:
  title: Identity providers (IDPs)
  version: v1
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
servers:
- url: https://{hostname}/crux/v1
tags:
- description: |
    Manage group membership within a directory.
  name: Directory membership
- description: |
    Manage Ghost to Origin (G2O) configurations.
  name: Ghost to Origin
- description: |
    Manage identity provider directories.
  name: IDP directories
- description: |
  Manage identity providers.
  name: IDPs
- description: |
  Manage SAML metadata.
  name: Metadata
- description: |
  Manage IdP status.
  name: Status
x-akamai:
  auth-type: EDGE_GRID
  file-path: 01-idp.yaml
paths:
  /mgmt-pop/idp:
    $ref: paths/idps.yaml
  /mgmt-pop/idp/{idp_id}:
    $ref: paths/idp.yaml
  /mgmt-pop/idp/{idp_id}/deploy:
    $ref: paths/deploy-idp.yaml
  /mgmt-pop/idp/{idp_id}/directories_membership:
    $ref: paths/directories-membership.yaml
  /mgmt-pop/idp/{idp_id}/g2o:
    $ref: paths/g2o-per-idp.yaml
  /mgmt-pop/idp/{idp_id}/metadata:
    $ref: paths/metadata.yaml
  /mgmt-pop/idp/{idp_id}/status:
    $ref: paths/status-per-idp.yaml
  /mgmt-pop/idpdirectory:
    $ref: paths/idp-directories.yaml
  /mgmt-pop/idpdirectory/{idpdirectory_id}:
    $ref: paths/idp-directory.yaml
