openapi: 3.0.0
info:
  title: Applications
  version: v1
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
servers:
- url: https://{hostname}/crux/v1
tags:
- description: |
  Manage application IDPs.
  name: Application IDPs
- description: |
  View application audit logs.
  name: Application audit logs
- description: |
  Manage application bundles.
  name: Application bundles
- description: |
    Manage application categories.
  name: Application categories
- description: |
    Manage application directories.
  name: Application directories
- description: |
  Manage application groups.
  name: Application groups
- description: |
    Manage application rewrite groups.
  name: Application rewrite groups
- description: |
  Manage applications.
  name: Applications
- description: |
  Block users.
  name: Block user
- description: |
  Manage connectors.
  name: Connectors
- description: |
  Manage edge keys.
  name: Edge keys
- description: |
    Manage Ghost to Origin (G2O) configurations.
  name: Ghost to Origin
- description: |
  Manage application services.
  name: Services
- description: |
  Manage URL location rules. 
  name: URL location rules
- description: |
  Unblock users.
  name: Unblock user
- description: |
  Manage versions. 
  name: Versions
x-akamai:
  auth-type: EDGE_GRID
  file-path: 03-apps.yaml
paths:
  /mgmt-pop/agents/{agentId}/app-metrics:
    $ref: paths/app-metrics.yaml
  /mgmt-pop/appbundle:
    $ref: paths/app-bundles.yaml
  /mgmt-pop/appbundle/{appBundleId}:
    $ref: paths/app-bundle.yaml
  /mgmt-pop/appbundle/{appBundleId}/deploy:
    $ref: paths/deploy-app-bundle.yaml
  /mgmt-pop/appcategories:
    $ref: paths/app-categories.yaml
  /mgmt-pop/appcategories/{appCategoryId}:
    $ref: paths/app-category.yaml
  /mgmt-pop/appdirectories:
    $ref: paths/app-directories.yaml
  /mgmt-pop/appdirectories/{appDirectoryId}:
    $ref: paths/app-directory.yaml
  /mgmt-pop/appgroups:
    $ref: paths/app-groups.yaml
  /mgmt-pop/appgroups/{appGroupId}:
    $ref: paths/app-group.yaml
  /mgmt-pop/appidp:
    $ref: paths/app-idps.yaml
  /mgmt-pop/appidp/{appIdpId}:
    $ref: paths/app-idp.yaml
  /mgmt-pop/application-reports/ops/query:
    $ref: paths/query.yaml
  /mgmt-pop/apps:
    $ref: paths/apps.yaml
  /mgmt-pop/apps/{applicationId}:
    $ref: paths/app.yaml
  /mgmt-pop/apps/{applicationId}/agents:
    $ref: paths/agents-per-app.yaml
  /mgmt-pop/apps/{applicationId}/agents/{agentId}:
    $ref: paths/agent.yaml
  /mgmt-pop/apps/{applicationId}/deploy:
    $ref: paths/deploy-app.yaml
  /mgmt-pop/apps/{applicationId}/edgekey:
    $ref: paths/edgekey.yaml
  /mgmt-pop/apps/{applicationId}/g2o:
    $ref: paths/g2o-per-app.yaml
  /mgmt-pop/apps/{applicationId}/groups:
    $ref: paths/groups-per-app.yaml
  /mgmt-pop/apps/{applicationId}/services:
    $ref: paths/services-per-app.yaml
  /mgmt-pop/apps/{applicationId}/urllocation:
    $ref: paths/url-location.yaml
  /mgmt-pop/apps/{applicationId}/urllocation/{locationId}:
    $ref: paths/location.yaml
  /mgmt-pop/apps/{applicationId}/versions:
    $ref: paths/versions.yaml
  /mgmt-pop/apps/{applicationId}/versions/{versionId}:
    $ref: paths/version.yaml
  /mgmt-pop/idpblockuser/idp/{idp_id}/block:
    $ref: paths/block.yaml
  /mgmt-pop/idpblockuser/idp/{idp_id}/unblock:
    $ref: paths/unblock.yaml
