openapi: 3.0.0
info:
  title: Adaptive Acceleration report
  version: v1
servers:
- url: https://{hostname}/adaptive-acceleration/v1
x-akamai:
  auth-type: EDGE_GRID
paths:
  /properties/{propertyId}:
    $ref: paths/property.yaml
  /properties/{propertyId}/reset:
    $ref: paths/reset.yaml
tags:
  - name: Property report
    description: |
      Get information about your Adaptive Acceleration report for an Ion property.