name: Content-Type
in: header
description: |
  Must be used to specify a request type.
required: true
schema:
  type: string
  example: application/vnd.akamai.cps.deployment-schedule.v1+json
  enum:
  - application/vnd.akamai.cps.deployment-schedule.v1+json
