x-akamai:
  file-path: paths/config-ase-penalty-box.yaml
  path-info: /configs/{configId}/versions/{versionNumber}/advanced-settings/ase-penalty-box
parameters:
- $ref: ../parameters/config-id-path.yaml
- $ref: ../parameters/version-number-path.yaml
get:
  operationId: get-ase-penalty-box-settings
  summary: Get ASE Penalty Box settings
  tags:
  - ASE Penalty Box
  description: |
    Return ASE Penalty Box settings for a specific configuration.
  x-akamai:
    labels:
    - Web Application Protector
    - Kona Site Defender
  responses:
    200:
      description: |
        Successfully retrieved the ASE Penalty Box settings.
      content:
        application/json:
          example:
            $ref: ../examples/ase-penalty-box-get-200.json
          schema:
            $ref: ../schemas/ase-penalty-box.yaml
    400:
      $ref: ../errors/400-client-read-errors.yaml
    404:
      $ref: ../errors/404-client-read-errors.yaml
    500:
      $ref: ../errors/500-server-errors.yaml
put:
  operationId: put-ase-penalty-box-settings
  summary: Modify ASE Penalty Box settings
  tags:
  - ASE Penalty Box
  description: |
    Update ASE Penalty Box settings for a specific configuration.
  x-akamai:
    labels:
    - Web Application Protector
    - Kona Site Defender
  requestBody:
    required: true
    content:
      application/json:
        example:
          $ref: ../examples/ase-penalty-box-put.json
        schema:
          $ref: ../schemas/ase-penalty-box.yaml
  responses:
    200:
      description: |
        Successfully updated the ASE Penalty Box settings.
      content:
        application/json:
          example:
            $ref: ../examples/ase-penalty-box-put-200.json
          schema:
            $ref: ../schemas/ase-penalty-box.yaml
    400:
      $ref: ../errors/400-client-read-errors.yaml
    403:
      $ref: ../errors/403-client-write-errors.yaml
    404:
      $ref: ../errors/404-client-read-errors.yaml
    500:
      $ref: ../errors/500-server-errors.yaml
