openapi: 3.0.0
info:
  title: Managed Services access control lists
  version: v1
servers:
- url: https://{hostname}/network-cloud-firewall/v1
tags:
- name: Managed Services ACLs
  description: |
    Returns the latest Managed Services ACL version.
x-akamai:
  auth-type: EDGE_GRID
paths:
  /policy-domains/{policyDomain}/managed-services-acls/version:
    $ref: paths/managed-services-acl.yaml