openapi: 3.0.0
info:
  title: Policies
  version: v1
servers:
- url: https://{hostname}/script-management/v1
tags:
- description: Groups operations that you can use to manage policies for your properties.
  name: Policies
x-akamai:
  auth-type: EDGE_GRID
paths:
  /properties/{propertyId}/hostnames/{hostname}/network/{network}/policies:
    $ref: paths/policies.yaml
